# Generated by Django 5.2.7 on 2025-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishly_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cate',
            field=models.CharField(choices=[('A', 'Arabi'), ('S', 'Shawerma'), ('B', 'Burgers'), ('D', 'Deserts'), ('I', 'Ice Cream')], default='A', max_length=1),
        ),
    ]
