# Generated by Django 5.2.7 on 2025-10-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishly_app', '0003_ingredient_alter_recipe_options_remove_recipe_cate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste a full recipe image https://URL'),
        ),
    ]
