# Generated by Django 5.2.7 on 2025-10-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishly_app', '0004_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste a full recipe image https://URL', max_length=500),
        ),
    ]
